const mongoose = require('mongoose');

const reportSchema = new mongoose.Schema(
  {
    reportId: {
      type: String,
      unique: true,
      uppercase: true,
      trim: true,
    },
    name: {
      type: String,
      required: [true, 'Report name is required'],
      trim: true,
    },
    type: {
      type: String,
      required: [true, 'Report type is required'],
      enum: {
        values: [
          'shipment',
          'financial',
          'client_performance',
          'container_utilization',
          'performance_analytics',
          'supplier_performance',
        ],
        message: 'Invalid report type',
      },
    },
    format: {
      type: String,
      required: [true, 'Report format is required'],
      enum: {
        values: ['pdf', 'excel', 'csv'],
        message: 'Invalid report format',
      },
      lowercase: true,
    },
    dateRange: {
      startDate: {
        type: Date,
        required: [true, 'Start date is required'],
      },
      endDate: {
        type: Date,
        required: [true, 'End date is required'],
      },
    },
    filters: {
      type: mongoose.Schema.Types.Mixed,
      default: {},
    },
    fileUrl: {
      type: String,
      default: '',
    },
    fileSize: {
      type: String, // Stored as "2.4 MB" format
    },
    generatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: [true, 'Generated by user is required'],
    },
    status: {
      type: String,
      enum: {
        values: ['generating', 'completed', 'failed'],
        message: 'Invalid report status',
      },
      default: 'generating',
    },
    metadata: {
      recordCount: {
        type: Number,
        default: 0,
      },
      totalValue: {
        type: Number,
      },
      parameters: {
        type: mongoose.Schema.Types.Mixed,
        default: {},
      },
    },
    downloadCount: {
      type: Number,
      default: 0,
    },
  },
  {
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
  }
);

// Indexes
reportSchema.index({ reportId: 1 }, { unique: true });
reportSchema.index({ type: 1 });
reportSchema.index({ generatedBy: 1 });
reportSchema.index({ createdAt: -1 });
reportSchema.index({ status: 1 });

// Auto-generate reportId before saving
reportSchema.pre('save', async function (next) {
  if (!this.reportId) {
    try {
      const lastReport = await this.constructor.findOne(
        {},
        {},
        { sort: { reportId: -1 } }
      );

      let nextNumber = 1;
      if (lastReport && lastReport.reportId) {
        const lastNumber = parseInt(lastReport.reportId.split('-')[1]);
        nextNumber = lastNumber + 1;
      }

      this.reportId = `RPT-${String(nextNumber).padStart(3, '0')}`;
    } catch (error) {
      return next(error);
    }
  }

  // Validate date range
  if (this.dateRange && this.dateRange.startDate && this.dateRange.endDate) {
    if (new Date(this.dateRange.startDate) > new Date(this.dateRange.endDate)) {
      return next(new Error('Start date must be before or equal to end date'));
    }
  }

  next();
});

// Virtual populate for generated by user details
reportSchema.virtual('generatedByUser', {
  ref: 'User',
  localField: 'generatedBy',
  foreignField: '_id',
  justOne: true,
});

const Report = mongoose.model('Report', reportSchema);

module.exports = Report;
