import { DashboardStats, RecentActivity, Client, Shipment, Container, Supplier, Report, RecentReport } from '@/types';

/**
 * Mock Data for Ceylon Cargo Transport Admin Dashboard
 */

// Dashboard Statistics
export const mockDashboardStats: DashboardStats = {
  totalRevenue: 18400000, // $18.4M
  activeShipments: 480,
  totalClients: 32,
  containersInUse: 3,
  completedShipments: 770,
  availableContainers: 2,
  pendingActions: 30,
};

// Recent Activities
export const mockRecentActivity: RecentActivity[] = [
  {
    id: '1',
    type: 'shipment',
    title: 'New shipment created',
    description: 'Acme Corporation',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000), // 2 hours ago
    icon: 'package',
  },
  {
    id: '2',
    type: 'container',
    title: 'Container CONT-462 marked as available',
    description: 'System',
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000), // 4 hours ago
    icon: 'box',
  },
  {
    id: '3',
    type: 'shipment',
    title: 'Shipment SHIP-002-2024 completed',
    description: 'Global Traders Ltd',
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000), // 6 hours ago
    icon: 'check-circle',
  },
  {
    id: '4',
    type: 'client',
    title: 'New client registered',
    description: 'Tech Import Co',
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000), // 1 day ago
    icon: 'user-plus',
  },
  {
    id: '5',
    type: 'container',
    title: 'Container CONT-460 in maintenance',
    description: 'System',
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000), // 1 day ago
    icon: 'wrench',
  },
];

// Top Performing Clients
export const mockTopClients: Pick<Client, 'id' | 'name' | 'shipmentsCount' | 'revenue'>[] = [
  {
    id: 'CLT-001',
    name: 'Automotive Parts Inc',
    shipmentsCount: 22,
    revenue: 6230000, // $6.23M
  },
  {
    id: 'CLT-002',
    name: 'Global Traders Ltd',
    shipmentsCount: 8,
    revenue: 4120000, // $4.12M
  },
  {
    id: 'CLT-003',
    name: 'Medical Supplies Co',
    shipmentsCount: 18,
    revenue: 2890000, // $2.89M
  },
  {
    id: 'CLT-004',
    name: 'Acme Corporation',
    shipmentsCount: 12,
    revenue: 2150000, // $2.15M
  },
];

// Fleet Utilization Data
export const mockFleetUtilization = {
  containersInUse: 50,
  availableCapacity: 33,
  maintenance: 17,
};

// Shipments Data
export const mockShipments: Shipment[] = [
  {
    id: 'SHIP-001-2024',
    clientId: 'CLT-001',
    client: {
      id: 'CLT-001',
      name: 'Acme Corporation',
      contactPerson: 'John Anderson',
      email: 'john.anderson@acme.com',
      phone: '+1 555-0123',
      location: 'New York, USA',
      shipmentsCount: 12,
      revenue: 2145000,
      rating: 4.8,
      status: 'active',
      createdAt: new Date('2024-01-15'),
    },
    origin: 'Shanghai, China',
    destination: 'Los Angeles, USA',
    departureDate: new Date('2024-10-15'),
    arrivalDate: new Date('2024-11-28'),
    containerId: 'CONT-458',
    container: {
      id: 'CONT-458',
      type: '40ft_high_cube',
      status: 'in_use',
      location: 'Pacific Ocean',
      shipmentId: 'SHIP-001-2024',
      capacity: 67.7,
      maxWeight: 28580,
      currentWeight: 2500,
      condition: 'excellent',
      createdAt: new Date('2023-01-10'),
    },
    cargoType: 'Electronics',
    weight: 2500,
    status: 'in_transit',
    createdAt: new Date('2024-10-15'),
  },
  {
    id: 'SHIP-002-2024',
    clientId: 'CLT-002',
    client: {
      id: 'CLT-002',
      name: 'Global Traders Ltd',
      contactPerson: 'Sarah Chen',
      email: 'sarah.chen@globaltraders.com',
      phone: '+44 20 7946 0958',
      location: 'London, UK',
      shipmentsCount: 8,
      revenue: 4120000,
      rating: 4.9,
      status: 'active',
      createdAt: new Date('2024-02-01'),
    },
    origin: 'Rotterdam, Netherlands',
    destination: 'New York, USA',
    departureDate: new Date('2024-10-24'),
    arrivalDate: new Date('2024-11-20'),
    containerId: 'CONT-459',
    container: {
      id: 'CONT-459',
      type: '40ft_standard',
      status: 'available',
      location: 'Colombo Port',
      capacity: 67.5,
      maxWeight: 26680,
      currentWeight: 0,
      condition: 'good',
      createdAt: new Date('2023-02-15'),
    },
    cargoType: 'Machinery',
    weight: 4200,
    status: 'completed',
    createdAt: new Date('2024-10-24'),
  },
  {
    id: 'SHIP-003-2024',
    clientId: 'CLT-003',
    client: {
      id: 'CLT-003',
      name: 'Tech Import Co',
      contactPerson: 'Michael Wong',
      email: 'michael.wong@techimport.sg',
      phone: '+65 6789 4561',
      location: 'Singapore',
      shipmentsCount: 15,
      revenue: 1790000,
      rating: 4.7,
      status: 'active',
      createdAt: new Date('2024-03-10'),
    },
    origin: 'Los Angeles, USA',
    destination: 'Singapore',
    departureDate: new Date('2024-10-25'),
    arrivalDate: new Date('2024-11-18'),
    containerId: 'CONT-460',
    container: {
      id: 'CONT-460',
      type: '20ft_standard',
      status: 'maintenance',
      location: 'Repair Facility',
      capacity: 33.2,
      maxWeight: 21750,
      currentWeight: 0,
      condition: 'under_repair',
      createdAt: new Date('2023-03-20'),
    },
    cargoType: 'Computer Parts',
    weight: 3800,
    status: 'pending',
    createdAt: new Date('2024-10-25'),
  },
  {
    id: 'SHIP-004-2024',
    clientId: 'CLT-004',
    client: {
      id: 'CLT-004',
      name: 'Fashion Imports',
      contactPerson: 'Isabella Rossi',
      email: 'i.rossi@fashionimports.it',
      phone: '+39 02 1234 5678',
      location: 'Milan, Italy',
      shipmentsCount: 0,
      revenue: 850000,
      rating: 4.5,
      status: 'inactive',
      createdAt: new Date('2024-04-05'),
    },
    origin: 'Milan, Italy',
    destination: 'Dubai, UAE',
    departureDate: new Date('2024-10-12'),
    arrivalDate: new Date('2024-11-23'),
    containerId: 'CONT-461',
    container: {
      id: 'CONT-461',
      type: '40ft_refrigerated',
      status: 'in_use',
      location: 'Atlantic Ocean',
      shipmentId: 'SHIP-004-2024',
      capacity: 67.3,
      maxWeight: 26580,
      currentWeight: 1900,
      condition: 'excellent',
      createdAt: new Date('2023-04-01'),
    },
    cargoType: 'Textiles',
    weight: 1900,
    status: 'in_transit',
    createdAt: new Date('2024-10-12'),
  },
  {
    id: 'SHIP-005-2024',
    clientId: 'CLT-005',
    client: {
      id: 'CLT-005',
      name: 'Automotive Parts Inc',
      contactPerson: 'Hiroshi Tanaka',
      email: 'h.tanaka@autoparts.jp',
      phone: '+81 3 1234 5678',
      location: 'Tokyo, Japan',
      shipmentsCount: 22,
      revenue: 6230000,
      rating: 5,
      status: 'active',
      createdAt: new Date('2024-05-12'),
    },
    origin: 'Tokyo, Japan',
    destination: 'Los Angeles, USA',
    departureDate: new Date('2024-08-28'),
    arrivalDate: new Date('2024-10-16'),
    containerId: 'CONT-462',
    container: {
      id: 'CONT-462',
      type: '20ft_high_cube',
      status: 'available',
      location: 'Dubai Port',
      capacity: 37.4,
      maxWeight: 21600,
      currentWeight: 0,
      condition: 'good',
      createdAt: new Date('2023-05-05'),
    },
    cargoType: 'Auto Parts',
    weight: 5800,
    status: 'completed',
    createdAt: new Date('2024-08-28'),
  },
  {
    id: 'SHIP-006-2024',
    clientId: 'CLT-006',
    client: {
      id: 'CLT-006',
      name: 'Medical Supplies Co',
      contactPerson: 'Dr Emma Schmidt',
      email: 'e.schmidt@medsupplies.de',
      phone: '+49 40 1234 5678',
      location: 'Hamburg, Germany',
      shipmentsCount: 18,
      revenue: 2890000,
      rating: 4.8,
      status: 'active',
      createdAt: new Date('2024-06-20'),
    },
    origin: 'Hamburg, Germany',
    destination: 'Cape Town, South Africa',
    departureDate: new Date('2024-10-30'),
    arrivalDate: new Date('2024-11-30'),
    containerId: 'CONT-463',
    container: {
      id: 'CONT-463',
      type: '40ft_standard',
      status: 'in_use',
      location: 'Indian Ocean',
      shipmentId: 'SHIP-006-2024',
      capacity: 67.5,
      maxWeight: 26680,
      currentWeight: 2100,
      condition: 'excellent',
      createdAt: new Date('2023-06-15'),
    },
    cargoType: 'Medical Equipment',
    weight: 2100,
    status: 'pending',
    createdAt: new Date('2024-10-30'),
  },
];

// Containers Data
export const mockContainers: Container[] = [
  {
    id: 'CONT-458',
    type: '40ft_high_cube',
    status: 'in_use',
    location: 'Pacific Ocean',
    shipmentId: 'SHIP-001-2024',
    capacity: 67.7,
    maxWeight: 28580,
    currentWeight: 2500,
    condition: 'excellent',
    createdAt: new Date('2023-01-10'),
  },
  {
    id: 'CONT-459',
    type: '40ft_standard',
    status: 'available',
    location: 'Colombo Port',
    capacity: 67.5,
    maxWeight: 26680,
    currentWeight: 0,
    condition: 'good',
    createdAt: new Date('2023-02-15'),
  },
  {
    id: 'CONT-460',
    type: '20ft_standard',
    status: 'maintenance',
    location: 'Repair Facility',
    capacity: 33.2,
    maxWeight: 21750,
    currentWeight: 0,
    condition: 'under_repair',
    createdAt: new Date('2023-03-20'),
  },
  {
    id: 'CONT-461',
    type: '40ft_refrigerated',
    status: 'in_use',
    location: 'Atlantic Ocean',
    shipmentId: 'SHIP-014-2024',
    capacity: 67.3,
    maxWeight: 26580,
    currentWeight: 3400,
    condition: 'excellent',
    createdAt: new Date('2023-04-01'),
  },
  {
    id: 'CONT-462',
    type: '20ft_high_cube',
    status: 'available',
    location: 'Dubai Port',
    capacity: 37.4,
    maxWeight: 21600,
    currentWeight: 0,
    condition: 'good',
    createdAt: new Date('2023-05-05'),
  },
  {
    id: 'CONT-463',
    type: '40ft_standard',
    status: 'in_use',
    location: 'Indian Ocean',
    shipmentId: 'SHIP-036-2024',
    capacity: 67.5,
    maxWeight: 26680,
    currentWeight: 2150,
    condition: 'excellent',
    createdAt: new Date('2023-06-15'),
  },
];

// Clients Data
export const mockClients: Client[] = [
  {
    id: 'CLT-001',
    name: 'Acme Corporation',
    contactPerson: 'John Anderson',
    email: 'john.anderson@acme.com',
    phone: '+1 555-0123',
    location: 'New York, USA',
    shipmentsCount: 12,
    revenue: 2145000,
    rating: 4.8,
    status: 'active',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'CLT-002',
    name: 'Global Traders Ltd',
    contactPerson: 'Sarah Chen',
    email: 'sarah.chen@globaltraders.com',
    phone: '+44 20 7946 0958',
    location: 'London, UK',
    shipmentsCount: 8,
    revenue: 4120000,
    rating: 4.9,
    status: 'active',
    createdAt: new Date('2024-02-01'),
  },
  {
    id: 'CLT-003',
    name: 'Tech Import Co',
    contactPerson: 'Michael Wong',
    email: 'michael.wong@techimport.sg',
    phone: '+65 6789 4561',
    location: 'Singapore',
    shipmentsCount: 15,
    revenue: 1790000,
    rating: 4.7,
    status: 'active',
    createdAt: new Date('2024-03-10'),
  },
  {
    id: 'CLT-004',
    name: 'Fashion Imports',
    contactPerson: 'Isabella Rossi',
    email: 'i.rossi@fashionimports.it',
    phone: '+39 02 1234 5678',
    location: 'Milan, Italy',
    shipmentsCount: 5,
    revenue: 850000,
    rating: 4.5,
    status: 'inactive',
    createdAt: new Date('2024-04-05'),
  },
  {
    id: 'CLT-005',
    name: 'Automotive Parts Inc',
    contactPerson: 'Hiroshi Tanaka',
    email: 'h.tanaka@autoparts.jp',
    phone: '+81 3 1234 5678',
    location: 'Tokyo, Japan',
    shipmentsCount: 22,
    revenue: 6230000,
    rating: 5,
    status: 'active',
    createdAt: new Date('2024-05-12'),
  },
  {
    id: 'CLT-006',
    name: 'Medical Supplies Co',
    contactPerson: 'Dr Emma Schmidt',
    email: 'e.schmidt@medsupplies.de',
    phone: '+49 40 1234 5678',
    location: 'Hamburg, Germany',
    shipmentsCount: 18,
    revenue: 2890000,
    rating: 4.8,
    status: 'active',
    createdAt: new Date('2024-06-20'),
  },
  {
    id: 'CLT-007',
    name: 'Pacific Exports',
    contactPerson: 'James Wilson',
    email: 'j.wilson@pacificexports.com.au',
    phone: '+61 2 9876 5432',
    location: 'Sydney, Australia',
    shipmentsCount: 10,
    revenue: 1520000,
    rating: 4.6,
    status: 'active',
    createdAt: new Date('2024-07-18'),
  },
  {
    id: 'CLT-008',
    name: 'Textile Traders',
    contactPerson: 'Priya Sharma',
    email: 'p.sharma@textiletraders.in',
    phone: '+91 22 1234 5678',
    location: 'Mumbai, India',
    shipmentsCount: 14,
    revenue: 1340000,
    rating: 4.4,
    status: 'active',
    createdAt: new Date('2024-08-22'),
  },
  {
    id: 'CLT-009',
    name: 'Construction Materials Ltd',
    contactPerson: 'Ahmed Hassan',
    email: 'a.hassan@constructionmaterials.ae',
    phone: '+971 4 123 4567',
    location: 'Dubai, UAE',
    shipmentsCount: 6,
    revenue: 980000,
    rating: 4.3,
    status: 'active',
    createdAt: new Date('2024-09-05'),
  },
  {
    id: 'CLT-010',
    name: 'Electronics Wholesale',
    contactPerson: 'Li Wei',
    email: 'l.wei@electronicswholesale.cn',
    phone: '+86 21 1234 5678',
    location: 'Shanghai, China',
    shipmentsCount: 2,
    revenue: 450000,
    rating: 4.2,
    status: 'inactive',
    createdAt: new Date('2024-10-12'),
  },
];

// Suppliers Data
export const mockSuppliers: Supplier[] = [
  {
    id: 'SUP-001',
    name: 'Maritime Shipping Lines',
    tradingName: 'MSL',
    contactPerson: 'Captain James Rodriguez',
    email: 'j.rodriguez@maritimelines.com',
    phone: '+1 555-0196',
    location: 'Miami, USA',
    serviceType: 'ocean_freight',
    shipmentsCount: 156,
    activeContracts: 8,
    rating: 5,
    status: 'active',
    createdAt: new Date('2023-01-15'),
  },
  {
    id: 'SUP-002',
    name: 'Global Container Services',
    tradingName: 'GCS',
    contactPerson: 'Linda Zhang',
    email: 'l.zhang@globalcontainer.com',
    phone: '+86 21 5555 8888',
    location: 'Shanghai, China',
    serviceType: 'container',
    shipmentsCount: 243,
    activeContracts: 12,
    rating: 4.9,
    status: 'active',
    createdAt: new Date('2023-02-20'),
  },
  {
    id: 'SUP-003',
    name: 'Atlantic Port Solutions',
    tradingName: 'APS',
    contactPerson: "David O'Connor",
    email: 'd.oconnor@atlanticport.com',
    phone: '+353 1 555 0123',
    location: 'Dublin, Ireland',
    serviceType: 'port_ops',
    shipmentsCount: 89,
    activeContracts: 5,
    rating: 4.7,
    status: 'active',
    createdAt: new Date('2023-03-10'),
  },
  {
    id: 'SUP-004',
    name: 'FastLog Trucking',
    tradingName: 'FLT',
    contactPerson: 'Ahmed Hassan',
    email: 'a.hassan@fastlog.ae',
    phone: '+971 4 555 7890',
    location: 'Dubai, UAE',
    serviceType: 'ground',
    shipmentsCount: 67,
    activeContracts: 0,
    rating: 4.3,
    status: 'inactive',
    createdAt: new Date('2023-04-05'),
  },
  {
    id: 'SUP-005',
    name: 'Pacific International Freight',
    tradingName: 'PIF',
    contactPerson: 'Yuki Yamamoto',
    email: 'y.yamamoto@pacificfreight.jp',
    phone: '+81 3 5555 1234',
    location: 'Yokohama, Japan',
    serviceType: 'air_sea',
    shipmentsCount: 312,
    activeContracts: 15,
    rating: 5,
    status: 'active',
    createdAt: new Date('2023-05-18'),
  },
  {
    id: 'SUP-006',
    name: 'EuroLog Warehousing',
    tradingName: 'ELW',
    contactPerson: 'Sophie Müller',
    email: 's.muller@eurolog.de',
    phone: '+49 40 5555 4321',
    location: 'Hamburg, Germany',
    serviceType: 'warehouse',
    shipmentsCount: 128,
    activeContracts: 6,
    rating: 4.8,
    status: 'active',
    createdAt: new Date('2023-06-22'),
  },
  {
    id: 'SUP-007',
    name: 'Customs Solutions Ltd',
    tradingName: 'CSL',
    contactPerson: 'Rajesh Patel',
    email: 'r.patel@customssolutions.in',
    phone: '+91 22 5555 6789',
    location: 'Mumbai, India',
    serviceType: 'customs',
    shipmentsCount: 198,
    activeContracts: 10,
    rating: 4.6,
    status: 'active',
    createdAt: new Date('2023-07-30'),
  },
  {
    id: 'SUP-008',
    name: 'InterCargo Express',
    tradingName: 'ICE',
    contactPerson: 'Maria Silva',
    email: 'm.silva@intercargo.br',
    phone: '+55 11 5555 9876',
    location: 'Santos, Brazil',
    serviceType: 'express',
    shipmentsCount: 176,
    activeContracts: 7,
    rating: 4.5,
    status: 'active',
    createdAt: new Date('2023-08-14'),
  },
];

// Reports Data
export const mockReports: Report[] = [
  {
    id: 'RPT-001',
    name: 'Shipment Report',
    type: 'shipment',
    description: 'Detailed overview of all shipments with status and performance metrics',
    supportedFormats: ['pdf', 'excel'],
    lastGenerated: new Date('2024-11-28'),
  },
  {
    id: 'RPT-002',
    name: 'Financial Report',
    type: 'financial',
    description: 'Revenue, expenses, and profit analysis across all operations',
    supportedFormats: ['pdf', 'excel'],
    lastGenerated: new Date('2024-11-27'),
  },
  {
    id: 'RPT-003',
    name: 'Client Performance Report',
    type: 'client_performance',
    description: 'Client activity, revenue contribution, and satisfaction ratings',
    supportedFormats: ['pdf', 'excel', 'csv'],
    lastGenerated: new Date('2024-11-26'),
  },
  {
    id: 'RPT-004',
    name: 'Container Utilization Report',
    type: 'container_utilization',
    description: 'Fleet usage statistics, availability, and maintenance schedules',
    supportedFormats: ['pdf', 'excel'],
    lastGenerated: new Date('2024-11-26'),
  },
  {
    id: 'RPT-005',
    name: 'Performance Analytics',
    type: 'performance_analytics',
    description: 'KPIs, trends, and operational efficiency metrics',
    supportedFormats: ['pdf', 'powerpoint'],
    lastGenerated: new Date('2024-11-25'),
  },
  {
    id: 'RPT-006',
    name: 'Supplier Performance Report',
    type: 'supplier_performance',
    description: 'Supplier ratings, on-time delivery rates, and contract status',
    supportedFormats: ['pdf', 'excel'],
    lastGenerated: new Date('2024-11-24'),
  },
];

export const mockRecentReports: RecentReport[] = [
  {
    id: 'RGEN-001',
    name: 'Monthly Shipment Summary - November 2024',
    type: 'shipment',
    generatedBy: 'Super Admin',
    date: new Date('2024-11-28'),
    size: '2.4 MB',
    format: 'pdf',
  },
  {
    id: 'RGEN-002',
    name: 'Q4 Financial Overview',
    type: 'financial',
    generatedBy: 'Finance Manager',
    date: new Date('2024-11-27'),
    size: '1.8 MB',
    format: 'excel',
  },
  {
    id: 'RGEN-003',
    name: 'Client Revenue Analysis - October 2024',
    type: 'client_performance',
    generatedBy: 'Sales Manager',
    date: new Date('2024-11-26'),
    size: '3.1 MB',
    format: 'pdf',
  },
  {
    id: 'RGEN-004',
    name: 'Container Fleet Status Report',
    type: 'container_utilization',
    generatedBy: 'Operations Manager',
    date: new Date('2024-11-25'),
    size: '1.5 MB',
    format: 'excel',
  },
  {
    id: 'RGEN-005',
    name: 'Weekly Performance Metrics',
    type: 'performance_analytics',
    generatedBy: 'Super Admin',
    date: new Date('2024-11-24'),
    size: '4.2 MB',
    format: 'pdf',
  },
];
